"""empty message

Revision ID: 8761d7ecddba
Revises: a5cffa318ac2
Create Date: 2026-07-25 00:43:46.591713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8761d7ecddba'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguidores',
    sa.Column('usuario_to_id', sa.Integer(), nullable=False),
    sa.Column('usuario_from_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_from_id'], ['Usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_to_id'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_to_id', 'usuario_from_id')
    )
    op.create_table('Comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text_coment', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['Usuarios.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['Publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('Post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Post_id'], ['Publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('media')
    op.drop_table('Comentarios')
    op.drop_table('seguidores')
    op.drop_table('Publicaciones')
    op.drop_table('Usuarios')
    # ### end Alembic commands ###
